# Generated by Django 5.1.3 on 2024-11-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='updated_at',
        ),
    ]
