# Generated by Django 5.1.3 on 2024-11-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_remove_expense_created_at_remove_expense_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date_of_expense',
            field=models.DateField(),
        ),
    ]
