# Generated by Django 5.1.3 on 2024-12-01 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_alter_expense_date_of_expense'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
